#!/usr/bin/env sh

set -eu

rubygems=${1:-}

if [ -n "$rubygems" ]
then
  gem update --system "$rubygems"
fi

gem install --no-document pkg/*.gem
cd "$(dirname "$(gem which argon2id)")/.."
bundle
bundle exec rake test
